import type { PlatformCapabilities } from "@/lib/providers/types";
import type { PlatformKey } from "./catalog";

/**
 * Per-platform capability + limit declarations. The composer reads these to show
 * character counters, gate media types, and warn on carousel limits.
 * Sources: each platform's current publishing API docs (2026).
 */
export const CAPABILITIES: Record<PlatformKey, PlatformCapabilities> = {
  facebook: {
    platform: "facebook",
    captionMax: 63206,
    media: { image: true, video: true, maxItems: 10, videoMaxSec: 3600 },
    supportsFirstComment: true,
    supportsScheduling: "internal",
    publish: true,
    comments: true,
    mentions: true,
    dms: true,
    analytics: true,
    scopes: [
      "pages_show_list",
      "pages_read_engagement",
      "pages_manage_posts",
      "pages_manage_engagement",
      "pages_messaging",
      "business_management",
      "read_insights",
    ],
    needsAppReview: true,
  },
  instagram: {
    platform: "instagram",
    captionMax: 2200,
    media: {
      image: true,
      video: true,
      maxItems: 20,
      videoMaxSec: 900,
      videoMinSec: 3,
    },
    supportsFirstComment: true,
    supportsScheduling: "internal",
    publish: true,
    comments: true,
    mentions: true,
    dms: true,
    analytics: true,
    scopes: [
      "instagram_basic",
      "instagram_content_publish",
      "instagram_manage_comments",
      "instagram_manage_insights",
      "pages_show_list",
      "business_management",
    ],
    needsAppReview: true,
    notes: "Two-step container publish. Business/Creator accounts only.",
  },
  linkedin: {
    platform: "linkedin",
    captionMax: 3000,
    media: { image: true, video: true, maxItems: 20, videoMaxSec: 1800 },
    supportsFirstComment: true,
    supportsScheduling: "internal",
    publish: true,
    comments: true,
    mentions: true,
    dms: false,
    analytics: true,
    scopes: ["openid", "profile", "email", "w_member_social"],
    needsAppReview: true,
    notes:
      "Personal posting via w_member_social. Company Pages + inbox need Community Management API review.",
  },
  tiktok: {
    platform: "tiktok",
    captionMax: 2200,
    media: { image: false, video: true, maxItems: 1, videoMaxSec: 600 },
    supportsFirstComment: false,
    supportsScheduling: "internal",
    publish: true,
    comments: false,
    mentions: false,
    dms: false,
    analytics: true,
    scopes: ["user.info.basic", "video.publish", "video.upload", "video.list"],
    needsAppReview: true,
    notes:
      "Uses Client Key (not Client ID). Redirect path must avoid brand names.",
  },
  youtube: {
    platform: "youtube",
    captionMax: 5000,
    media: { image: false, video: true, maxItems: 1, videoMaxSec: 43200 },
    supportsFirstComment: true,
    supportsScheduling: "native",
    publish: true,
    comments: true,
    mentions: false,
    dms: false,
    analytics: true,
    scopes: [
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtube.force-ssl",
      "https://www.googleapis.com/auth/yt-analytics.readonly",
    ],
    needsAppReview: true,
  },
  telegram: {
    platform: "telegram",
    captionMax: 4096,
    media: { image: true, video: true, maxItems: 10, videoMaxSec: 3600 },
    supportsFirstComment: false,
    supportsScheduling: "internal",
    publish: true,
    comments: false,
    mentions: false,
    dms: false,
    analytics: false,
    scopes: [],
    needsAppReview: false,
    notes: "Bot API. The bot must be an admin of the target channel.",
  },
};
